# Docker produccion o stage
FROM golang:1.14.3-buster

WORKDIR /go/src/github.com/hoxito/statsgo
RUN curl -L https://github.com/hoxito/statsgo/tarball/master | tar xz --strip=1
RUN go install

ENV MONGO_URL mongodb://host.docker.internal:27017
ENV RABBIT_URL amqp://host.docker.internal

# Puerto de Auth Service
EXPOSE 3000

CMD ["authgo"]

